### ISSUE TITLE
Meteor.Error object should be passed on the promise.reject call

### ISSUE THREAD

**Issue by davidyaha** [netanelgilad/angular-meteor-server#1]
Hey Netanel!

You are currently passing the Meteor.Error.details field. This makes implementations like putting the reason field as the headline of the error message impossible. You should consider passing the whole Error object instead.

Thanks for this awesome package!

**Comment by netanelgilad** [comment]
You are totally correct. It was a temporary fix but then I went for 3 months :). I'll get to taking care of this better.

**Comment by netanelgilad** [comment]
Fixed in 1.4.5
