### ISSUE TITLE
AngularJS 2 support?

### ISSUE THREAD

**Issue by KeithGillette** [netanelgilad/angular-meteor-server#17]
Is there an `angular2-meteor-server` or equivalent for running Angular2 code on the server?

**Comment by netanelgilad** [comment]
Nope, actually not. 
I have stopped using Meteor, so I don't keep on maintaining it.
I do use @anguler/core on the server side in my node projects, but I haven't made that up into a package. Since meteor supports npm nicely now, I think that you could use @angular/core on the server side pretty easily. (Though to get the smart service sync between server and client it would still require a package of this kind).

**Comment by KeithGillette** [comment]
Thanks for the reply. Any pointers on how to bootstrap Angular2 under node.js greatly appreciated. I'm interested in using Angular to manage dependency injection on server code.

**Comment by KeithGillette** [comment]
To answer my own more limited question of how to use AngularJS 2 dependency injection under node.js, I discovered it was quite easy and possible with only AngularJS 2 `@angular/core` packages. Classes providing injectable services need only be annotated as `@Injectable()` and then these imported and registered with the AngularJS 2 injector, which is invoked in the main entry point of the application. After that, AngularJS dependency injection takes care of locating and instantiating the relevant services, per the example below.

**api.service.ts**
```
import { Injectable } from '@angular/core';

/***
 * @description     @Injectable() service providing client API
 */
@Injectable()
export class ApiService {

    public start(): void {
        // @ToDo: do stuff
    }
}
```

**server.service.ts**
```
import { Injectable } from '@angular/core';

import { ApiService } from './core/application/api.service';

/***
 * @description     @Injectable() service creating main server instance
 */
@Injectable()
export class ServerService {
    constructor(private ApiService: ApiService) {   }

    public start(): void {
        this.apiService.start();
        // @ToDo: other stuff

    }
}
```

**server.injector.ts**
```
import { Provider } from '@angular/core';
import { ReflectiveInjector } from '@angular/core';

import { ApiService, ServerService } from '../../application';

const providers: Provider[] = [ServerService, ApiService];
export const injector = ReflectiveInjector.resolveAndCreate(providers);
```

**main.ts**
```
import 'reflect-metadata';

import { ServerService } from './imports/server.service';
import {injector} from './imports/core/infrastructure/dependency-injection/server.injector';

const server: ServerService = injector.get(ServerService);
server.start();
```

_Now to find out how to implement the AngularJS 2 module system on the server or otherwise structure hierarchical injectors …_

**Comment by netanelgilad** [comment]
Exactly like I did it. I created some more decorators for myself to make registering classes with the injector easier, so maybe one day I'll turn it into a package. Great example @KeithGillette 🍻
