### ISSUE TITLE
Unknown Provider

### ISSUE THREAD

**Issue by jaypanares** [netanelgilad/angular-meteor-server#2]
Hi, trying to register services using the code below:

```
angular
  .module('crave.collector.services')
  .config(APIConfig);

function APIConfig(ServerAPIProvider) {
  ServerAPIProvider.register('ServiceA');
  ServerAPIProvider.register('ServiceB');
}
```

but I get the error that `ServiceB` is an unknown provider even though it is defined in the server.  Is it possible to register multiple services using `ServerAPIProvider`?

Thanks!

**Comment by netanelgilad** [comment]
Yes there should not be a problem to register more then one service. I believe I have done so in the example. Can you share a reproduction so I can check it out?

**Comment by netanelgilad** [comment]
Hey @jaypanares ,
I'm closing this because of no response. But feel free to re-open if you still need help.
