### ISSUE TITLE
Bootstrap package app

### ISSUE THREAD

**Issue by 4shaw** [netanelgilad/angular-meteor-server#8]
Hey Netanel

Trying to bootstrap a package causes issues if the main app or any other package has already bootstrapped. I get:  App Already Bootstrapped with this Element 'document'

Is it possible to create a meteor package that uses angular-server

Thanks

**Comment by netanelgilad** [comment]
Hey @4shaw ,
Are you creating a packages that uses angular-server and supplies services for applications? I guess that if so, why are you trying to bootstrap an application?
I can't tell exactly where in your code your doing it, but it seems you are trying to bootstrap an application in more than one place. Make sure that if you bootstrap on the server a different module, that you don't also bootstrap on the client, causing a conflict with the client bootstrapping (maybe by ng-app?)
If you can sure your code, I can take a look.
Cheers!

**Comment by 4shaw** [comment]
Hey Netanel, thank you for your response. I might just be thinking about this all wrong.

I think the best way to explain my situation is to imagine converting the example app you have provided (todomvc) into a package. In that package you would not be able to bootstrap because the main app would conflict.

If I create a package and leave out the bootstrap would the server side services still work?

Thanks!

**Comment by netanelgilad** [comment]
If you leave out the bootstrap part, then the application that uses your package has to bootstrap the server side itself.

**Comment by 4shaw** [comment]
OK great thank you... I understand better now ;)
